name: flutter_tags
description: Creating selectable and input tags (TextField) has never been easier.
version: 1.0.1+1
homepage: https://github.com/Dn-a/flutter_tags/tree/null-safety

environment:
  sdk: '>=2.17.1 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
